In [1]:
def check():
    print("Working fine")

print("Notebook Started")
check()

Notebook Started
Working fine

In [2]:
import pandas as pd

df = pd.read_csv("power_grid_corporation\power_grid_corp_power_demand.csv")

df.head()

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
C:\Users\admin\AppData\Local\Temp\ipykernel_13524\3952664551.py:3: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv("power_grid_corporation\power_grid_corp_power_demand.csv")

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal
0,2015-04-19 22:00:00,6323.0,6323,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
1,2015-04-19 21:00:00,6667.0,6667,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2,2015-04-19 19:00:00,6897.0,6897,0,4415,1836,161,41,NaN,NaN,444,0,NaN,NaN
3,2015-04-19 18:30:00,6933.0,6933,0,4423,1862,159,45,NaN,NaN,444,0,NaN,NaN
4,2015-04-19 18:00:00,6874.0,6874,0,4319,1892,155,65,NaN,NaN,443,0,NaN,NaN

**Since we are working on a time series analysis. we have to sort with the respect to time**

In [5]:
df.set_index('datetime', inplace=True)

df.sort_index(inplace=True)
df.head()

,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal
datetime,,,,,,,,,,,,,
2015-04-19 00:00:00,4821.0,4821,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2015-04-19 01:00:00,3612.0,3612,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2015-04-19 02:00:00,3727.0,3727,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2015-04-19 03:00:00,3632.0,3632,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN
2015-04-19 04:00:00,3641.0,3641,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN

In [6]:
df.shape

(92218, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92218 entries, 2015-04-19 00:00:00 to 2025-06-17 12:00:00
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   generation_mw         92218 non-null  float64
 1   demand_mw             92218 non-null  int64
 2   load_shedding         92218 non-null  int64
 3   gas                   92218 non-null  int64
 4   liquid_fuel           92218 non-null  int64
 5   coal                  92218 non-null  int64
 6   hydro                 92218 non-null  int64
 7   solar                 70330 non-null  float64
 8   wind                  18656 non-null  float64
 9   india_bheramara_hvdc  92218 non-null  int64
 10  india_tripura         92218 non-null  int64
 11  india_adani           7332 non-null   float64
 12  nepal                 5347 non-null   float64
dtypes: float64(5), int64(8)
memory usage: 9.8+ MB

**the values that are nan mean no data for this we can change it to 0**

In [ ]:
df['solar'].fillna(0, inplace=True)
df['wind'].fillna(0, inplace=True)
df['india_adani'].fillna(0, inplace=True)
df['nepal'].fillna(0, inplace=True)
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 92218 entries, 2015-04-19 00:00:00 to 2025-06-17 12:00:00
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   generation_mw         92218 non-null  float64
 1   demand_mw             92218 non-null  int64
 2   load_shedding         92218 non-null  int64
 3   gas                   92218 non-null  int64
 4   liquid_fuel           92218 non-null  int64
 5   coal                  92218 non-null  int64
 6   hydro                 92218 non-null  int64
 7   solar                 92218 non-null  float64
 8   wind                  92218 non-null  float64
 9   india_bheramara_hvdc  92218 non-null  int64
 10  india_tripura         92218 non-null  int64
 11  india_adani           92218 non-null  float64
 12  nepal                 92218 non-null  float64
dtypes: float64(5), int64(8)
memory usage: 11.9+ MB

C:\Users\admin\AppData\Local\Temp\ipykernel_13524\1240337007.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['solar'].fillna(0, inplace=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_13524\1240337007.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['wind'].fillna(0, inplace=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_13524\1240337007.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['india_adani'].fillna(0, inplace=True)
C:\Users\admin\AppData\Local\Temp\ipykernel_13524\1240337007.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['nepal'].fillna(0, inplace=True)

In [9]:
df.head()

,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal
datetime,,,,,,,,,,,,,
2015-04-19 00:00:00,4821.0,4821,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0
2015-04-19 01:00:00,3612.0,3612,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0
2015-04-19 02:00:00,3727.0,3727,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0
2015-04-19 03:00:00,3632.0,3632,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0
2015-04-19 04:00:00,3641.0,3641,0,0,0,0,0,0.0,0.0,0,0,0.0,0.0